# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WikySearch' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WikySearch

	pod 'Alamofire'
	pod 'SwiftyJSON'

  target 'WikySearchTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'WikySearchUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
